### PR TITLE
use libsquashfuse_ll for non-setuid version

### PR DESCRIPTION
**Pull request by simonpintarelli**
if setreuid(0,0) fails, attempt to mount using squashfuse:

1) do the same as "unshare --mount --map-root-user"
2) fork(), in child process: mount squashfs image via libsquashfuse_ll (equivalent to `squashfuse_ll` executable)
3) ignore SIGINT (ctrl-c) in child process (otherwise pressing CTRL-C in theshell would unmount the fs)
4) restore original user, group id
5) call execvp
6) when shell is closed: kill child process running `fuse_session_loop` (via `prctl(PR_SET_PDEATHSIG, SIGHUP)`)

**meson**
- add option for fuse2/3 `-Dfuse_version=fuse|fuse3` to meson
- make suid install optional `-Dsuid=true|false`
- disable code for rootless version when `-Dsuid=true`

**CI**
- add dependencies for squashfs in ubuntu docker libfuse-dev, install squashfuse@0.1.105 from source
- test-mount.sh: run in a temporary directory (avoid sudo mkdir /mountpoint)
- add test for squashfuse branch

**rpmbuild**
- add source files to generate-rpm.sh
- Squashfuse is not available in suse packages. Install squashfuse (static libraries) manually.
- install all compression libraries supported by
squashfuse (xz|lzo|zstd|lz4)-devel (pass via LDFLAGS to Makefile)
- link statically against squashfuse (which was installed from source)

### CODE REVIEW

**Comment by haampie** [comment]
Would splitting the setuid / rootless version into two separate executables make sense? (And then have an option to not build the setuid version). Previously I thought the rootless version was a nice (but slow) fallback, now that we know performance is decent, it's probably a great standalone tool. Combining the setuid & rootless logic is a bit of an overhead in the sense that we'd have to review the changes to rootless code while keeping in mind it _could_ maybe run as root...

**Comment by haampie** [comment]
We got to fix squashfuse since it installs its own config.h which among other things overrides `#define VERSION`

**Comment by simonpintarelli** [comment]
> We got to fix squashfuse since it installs its own config.h which among other things overrides `#define VERSION`

I forgot to remove `#include <squashfuse_ll.h>` in the `squashfs-mount.c`, the version is now printed correctly from what is passed with `-DVERSION`.

**Comment by ocaisa** [comment]
Do you have a timeframe for when this might be ready for merge, we are looking at `squashfs-mount-rootless` as an easy-to-document option for sites that don't/can't/won't provide CernVM-FS. We are considering to shrinkwrap our repo ([EESSI](http://www.eessi.io/docs/)), export to SquashFS and make it available for users to mount on those systems in userspace.

**Comment by ocaisa** [comment]
Thanks, we'll look into it.

I guess the primary issue here for us is security, and if we approach EuroHPC sites with a solution that requires SUID they may be turned off (particularly if they are ISO certified). We could ship a rootless build with EasyBuild, but we'd probably still have to convince them to introduce the mounts into their SLURM prolog/epilog scripts for MPI to work.

**Comment by simonpintarelli** [comment]
An updated PR rebased to the current master branch is here:
https://github.com/eth-cscs/squashfs-mount/pull/24

**Pull request closed without merging**
